version: 0.2
phases:
  build:
    commands:
      # Todo parametrize bucket name
      - pip install --upgrade --user awscli
      - aws --version
      - aws cloudformation package --template-file deploy/stack.yaml
                                   --s3-bucket thebestest-pipeline
                                   --output-template-file stack_deploy.yaml
artifacts:
  type: zip
  files:
    - stack_deploy.yaml
