AWSTemplateFormatVersion: 2010-09-09
Description: A pipeline to test and validate TheBestest Code
Resources:
  theBestestPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref AWS::StackName
      ArtifactStore:
        Location: !ImportValue theBestest-pipelineBucket
        Type: S3
      RoleArn: !ImportValue theBestest-pipelineRoleArn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                S3Bucket: !ImportValue theBestest-pipelineBucket
                S3ObjectKey: thebestest-source.zip
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: thebestest-source
        - Name: UnitTest
          Actions:
            - Name: UnitTest
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !ImportValue theBestest-theBestestUnitTestId
              InputArtifacts:
                - Name: thebestest-source






