AWSTemplateFormatVersion: 2010-09-09
Description: Pipeline for TheBestest App
Resources:
  theBestestPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: thebestest-prod-pipeline
      ArtifactStore:
        Location: !ImportValue theBestest-pipelineBucket
        Type: S3
      RoleArn: !ImportValue theBestest-pipelineRoleArn
      Stages:
        - Name: Source
          Actions:
            - Name: Master
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: nimbusscale
                OAuthToken: !ImportValue theBestest-OAuthToken
                Repo: TheBestest
                Branch: master
                PollForSourceChanges: true
              OutputArtifacts:
                - Name: thebestest-source
        - Name: UnitTest
          Actions:
            - Name: UnitTest
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !ImportValue theBestest-theBestestUnitTestId
              InputArtifacts:
                - Name: thebestest-source
        - Name: Package
          Actions:
            - Name: Package
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !ImportValue theBestest-theBestestBuildId
              InputArtifacts:
                - Name: thebestest-source
              OutputArtifacts:
                - Name: thebestest-deploy-template
        - Name: DeployStack
          Actions:
            - Name: CreateChangeSet
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                StackName: thebestest-stack
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_IAM
                ChangeSetName: thebestest-stack-changeset
                TemplatePath: thebestest-deploy-template::stack_deploy.yaml
                RoleArn: !ImportValue theBestest-cloudformationRoleArn
              InputArtifacts:
                - Name: thebestest-deploy-template
            - Name: ExecuteChangeSet
              RunOrder: 2
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                StackName: thebestest-stack
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: thebestest-stack-changeset
            - Name: DeployApi
              RunOrder: 3
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Provider: Lambda
                Version: 1
              Configuration:
                FunctionName: !ImportValue theBestest-deployApiFunctionId
                UserParameters: "{\"stackName\": \"thebestest-stack\", \"stageName\": \"thebestest\"}"






