AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket used by TheBestest Pipeline
Resources:
  pipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: thebestest-pipeline
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 7
            NoncurrentVersionExpirationInDays: 1
            Status: Enabled
Outputs:
  bucketId:
    Value: !Ref pipelineBucket
    Export:
      Name: theBestest-pipelineBucket





