AWSTemplateFormatVersion: 2010-09-09
Description: Stack for TheBestest App
Parameters:
  EnvName:
    Description: Name of the environment to be deployed
    Type: String
    Default: "testing"
Resources:
###############################################################################
## Roles
###############################################################################
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BestestDbAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:DeleteItem
                  - dynamodb:GetItem
                  - dynamodb:GetRecords
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ItemTable}"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  StageDeployerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: pipelinePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:*
                Resource: !Sub "arn:aws:apigateway:${AWS::Region}::/restapis/${ApiGw}/*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

###############################################################################
## API Infra and User Pool
###############################################################################
  ApiGw:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub thebestest-${EnvName}-api
      Description: Rest API for the bestest

  ApiAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: userpool
      RestApiId: !Ref ApiGw
      IdentitySource: method.request.header.Authorization
      Type: COGNITO_USER_POOLS
      ProviderARNs:
        - !GetAtt UserPool.Arn

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub thebestest-${EnvName}-userpool
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false

  AdminClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub thebestest-${EnvName}-adminclient
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH

###############################################################################
## DynamoDB Tables
###############################################################################
  ItemTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub thebestest_${EnvName}_items
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: category_name
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: category_name
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

###############################################################################
## API Resources and Functions
###############################################################################

# /items
  ItemsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGw.RootResourceId
      PathPart: items
      RestApiId: !Ref ApiGw

# GET /items
  GetItemsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGw
      ResourceId: !Ref ItemsResource
      HttpMethod: GET
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiAuthorizer
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetItemsFunction.Arn}/invocations"
        PassthroughBehavior: WHEN_NO_TEMPLATES
        RequestTemplates:
          application/json: "{\"data\": \"\", \"metadata\" : { \"requestId\" : \"$context.requestId\", \"userId\": \"$context.authorizer.claims.sub\" }}"
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200

  GetItemsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../functions/get_items
      Environment:
        Variables:
          itemsTableName: !Ref ItemTable
      Handler: get_items.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.6

  GetItemsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGw}/*/GET/items"
      FunctionName: !Ref GetItemsFunction
      Action: lambda:InvokeFunction

###############################################################################
## Stage Deployer
###############################################################################

  StageDeployerLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../pipeline/functions/apigw_stage_deployer
      Handler: apigw_stage_deployer.deploy_stage
      Role: !GetAtt StageDeployerLambdaRole.Arn
      Runtime: python3.6

  ApiGwStageDeployer:
    Type: Custom::ApiGwStageDeployer
    Properties:
      ServiceToken: !GetAtt StageDeployerLambda.Arn
      StageName: thebestest
      RestApiId: !Ref ApiGw
      # Used to make sure this custom resource is updated when
      # methods are updated
      RestApiMethods: !Sub |
        { "methods": [
            "${GetItemsMethod}
          ]
        }

###############################################################################
## Outputs
###############################################################################

Outputs:
  UserPoolId:
    Value: !Ref UserPool
  AdminClientId:
    Value: !Ref AdminClient
  ApiGwId:
    Value: !Ref ApiGw

