AWSTemplateFormatVersion: 2010-09-09
Description: Stack for TheBestest App
Parameters:
  envName:
    Description: Name of the environment to be deployed
    Type: String
Resources:
###############################################################################
## Roles
###############################################################################
  lambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BestestDbAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:DeleteItem
                  - dynamodb:GetItem
                  - dynamodb:GetRecords
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${itemTable}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  stageDeployerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: pipelinePolicy
          PolicyDocument:
            Version: 2012-10-17
            # Todo Lock down
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:*
                Resource: "*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

###############################################################################
## API Infra and User Pool
###############################################################################
  apiGw:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub thebestest-${envName}-api
      Description: Rest API for the bestest

  apiAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: userpool
      RestApiId: !Ref apiGw
      IdentitySource: method.request.header.Authorization
      Type: COGNITO_USER_POOLS
      ProviderARNs:
        - !GetAtt userPool.Arn

  userPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub thebestest-${envName}-userpool
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false

  adminClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub thebestest-${envName}-adminclient
      UserPoolId: !Ref userPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH

###############################################################################
## DynamoDB Tables
###############################################################################
  itemTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub thebestest_${envName}_items
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: category_name
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: category_name
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

###############################################################################
## API Resources and Functions
###############################################################################

# /items
  itemsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt apiGw.RootResourceId
      PathPart: items
      RestApiId: !Ref apiGw

# GET /items
  getItemsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref apiGw
      ResourceId: !Ref itemsResource
      HttpMethod: GET
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref apiAuthorizer
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${getItemsFunction.Arn}/invocations"
        PassthroughBehavior: WHEN_NO_TEMPLATES
        RequestTemplates:
          application/json: "{\"data\": \"\", \"metadata\" : { \"requestId\" : \"$context.requestId\", \"userId\": \"$context.authorizer.claims.sub\" }}"
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200

  getItemsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../functions/get_items
      Environment:
        Variables:
          itemsTableName: !Ref itemTable
      Handler: get_items.lambda_handler
      Role: !GetAtt lambdaRole.Arn
      Runtime: python3.6

  getItemsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${apiGw}/*/GET/items"
      FunctionName: !Ref getItemsFunction
      Action: lambda:InvokeFunction

###############################################################################
## Stage Deployer
###############################################################################

  stageDeployerLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../pipeline/functions/apigw_stage_deployer
      Handler: apigw_stage_deployer.deploy_stage
      Role: !GetAtt stageDeployerLambdaRole.Arn
      Runtime: python3.6

  apiGwStageDeployer:
    Type: Custom::apiGwStageDeployer
    Properties:
      ServiceToken: !GetAtt stageDeployerLambda.Arn
      StageName: thebestest
      RestApiId: !Ref apiGw
      # Used to make sure this custom resource is updated when
      # methods are updated
      RestApiMethods: !Sub |
        { "methods": [
            "${getItemsMethod}
          ]
        }

###############################################################################
## Outputs
###############################################################################

Outputs:
  userPoolId:
    Value: !Ref userPool
  adminClientId:
    Value: !Ref adminClient
  apiGwId:
    Value: !Ref apiGw

